### ISSUE TITLE
Top-scope variable warning for lambda with DOS line endings

### ISSUE THREAD

**Issue by sevendials** [rodjek/puppet-lint#791] opened 2017-12-26 22:07 UTC
I noticed in our code that a .pp file with crlf line endings was causing puppet-lint to mistake an each block variable for a top-scope variable. I've distilled it down to the code below.
```
#
#
#
define foo {
  ['foo'].each |$bar| {
    file { "/bin/${bar}":
      content => $bar
    }
  }
}
```
After running `unix2dos foo.pp`, the above file causes puppet-lint to print two extra warnings:
```
/tmp/foo.pp|6 warning| [variable_scope] top-scope variable being used without an explicit namespace
/tmp/foo.pp|7 warning| [variable_scope] top-scope variable being used without an explicit namespace
```
The comment lines at the start of the file seem to matter. Removing one of them silences the second warning.

**Comment by rodjek** [comment] 2018-03-25 22:42
Duplicate of #778 (fixed in #782)

**Closed by rodjek** 2018-03-25 22:42 UTC
