### ISSUE TITLE
block-local variables (|$x|) don't properly get recognized when used as arrays or hashes

### ISSUE THREAD

**Issue by jearls** [rodjek/puppet-lint#450] opened 2015-10-09 18:21 UTC
The following fails the lint check:

    class t {
      $foo = { x => [1,3,5] , y => [2,4,6] }
      $bar = $foo.filter |$k, $v| { $v[0] % 2 == 0 }
      notify { "bar=<${bar}>": }
    }

The message is

    manifests/init.pp - WARNING: top-scope variable being used without an explicit namespace on line 4

If you change the offending line to:

      $bar = $foo.filter |$k, $v| { $vv = $v ; $vv[0] % 2 == 0 }

it passes lint.

**Comment by matonb** [comment] 2015-11-04 09:48
I've run into this issue as well.

**Comment by rnelson0** [comment] 2016-08-18 19:42
Duplicate of #464 (and #456) which has more discussion.

**Closed by rnelson0** 2016-08-18 19:42 UTC
