### ISSUE TITLE
Current package

### ISSUE THREAD

**Issue by Slm0n87** [rodjek/puppet-lint#471] opened 2016-04-25 08:19 UTC
Hi, latest available gem-package is 1.1.0. Which is also the latest tag here with latest commit from 23 Sep 2014  
Is it planned to set a newer stable tag? Or should I (as a puppet-lint user) use the master? 

Thx and Greets
Slm0n

**Comment by rnelson0** [comment] 2016-06-16 12:45
Duplicate of #443

@Slm0n87 Please point to master for now, and vote on the other issue.

**Closed by rnelson0** 2016-06-16 12:45 UTC
