### ISSUE TITLE
puppet-lint crash

### ISSUE THREAD

**Issue by alaunay** [rodjek/puppet-lint#422] opened 2015-04-30 13:47 UTC
Hello, the following (very badly written) code makes puppet-lint 1.1.0 crashes:

```
$ cat test.pp 
class test {
  package { 'something': ensure => purged,
    notify => Service['foobar'],
  }
}
$ puppet-lint test.pp 
/usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:115:in `[]': no implicit conversion from nil to integer (TypeError)
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:115:in `block (2 levels) in check'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:111:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:111:in `each_with_index'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:111:in `block in check'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:95:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/plugins/check_whitespace.rb:95:in `check'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checkplugin.rb:21:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:58:in `block in run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:56:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/checks.rb:56:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint.rb:168:in `run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:59:in `block in run'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `each'
	from /usr/lib/ruby/vendor_ruby/puppet-lint/bin.rb:56:in `run'
	from /usr/bin/puppet-lint:7:in `<main>'
$ puppet-lint --version
puppet-lint 1.1.0
```

**Comment by lucacri** [comment] 2015-05-14 20:47
+1

**Comment by rj667** [comment] 2015-05-18 11:07
This is a duplicate of #370 which is marked as closed, but the issue is not fixed.

**Comment by mrsmn** [comment] 2015-06-04 13:50
:+1:

**Comment by TimFerrell** [comment] 2015-06-09 15:05
+1

**Comment by brandfocus** [comment] 2015-06-12 13:10
+1

**Comment by paskal** [comment] 2015-07-21 12:14
Exactly same error for me.

**Comment by keeleysam** [comment] 2015-07-23 04:44
+1 @antoncohen

**Comment by hexathos** [comment] 2015-07-27 18:32
Having the same problem.

if interested i can provide the oiginal file

**Comment by Project0** [comment] 2015-08-18 07:54
seems to be an common problem, the linter should be able to handle this kind of errors.
I have something similar with quotes which are note closed:

```
class test {
    file { 'myfile':
        ensure => present,
        mode   => "0644,
    }
}
```

```
 /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/lexer.rb:323:in `initialize': no implicit conversion of nil into String (TypeError)
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/lexer.rb:323:in `new'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/lexer.rb:323:in `interpolate_string'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/lexer.rb:183:in `tokenise'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:25:in `load_data'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:53:in `run'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:168:in `run'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:59:in `block in run'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `each'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `run'
 	from /data/home/<user>/.gem/ruby/2.2.0/gems/puppet-lint-1.1.0/bin/puppet-lint:7:in `<top (required)>'
 	from /data/home/<user>/.gem/ruby/2.2.0/bin/puppet-lint:23:in `load'
 	from /data/home/<user>/.gem/ruby/2.2.0/bin/puppet-lint:23:in `<main>'
```

**Comment by ghoneycutt** [comment] 2015-08-18 17:44
-1

This is a syntax validation issue, not a style issue. Suggest that you run puppet-lint after successfully validating the syntax.

This can be accomplished with
``` bash
rake validate && rake lint
```


From the README
```
The goal of this project is to implement as many of the recommended Puppet style
guidelines from the Puppet Labs style guide as practical. It is not meant to validate
syntax. Please use puppet parser validate for that.
```

**Comment by Perdjesk** [comment] 2015-09-07 15:32
This seems not to be a syntax related issue as @ghoneycutt mentioned. Or at least not one that 'puppet parser validate' would catch.

```
$ cat test.pp 
class test {
  package { 'something': ensure => purged,
    notify => Service['foobar'],
  }
}

$ puppet parser validate --debug test.pp
Debug: Runtime environment: puppet_version=3.7.2, ruby_version=2.1.2, run_mode=user, default_encoding=UTF-8

$ puppet-lint test.pp 
/var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `[]': no implicit conversion from nil to integer (TypeError)
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `block (2 levels) in check'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each_with_index'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `block in check'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `check'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checkplugin.rb:21:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:58:in `block in run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:168:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `each'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `run'
	from /var/lib/gems/2.1.0/gems/puppet-lint-1.1.0/bin/puppet-lint:7:in `<top (required)>'
	from /usr/local/bin/puppet-lint:23:in `load'
	from /usr/local/bin/puppet-lint:23:in `<main>'


```

**Comment by Perdjesk** [comment] 2015-09-07 18:34
By reading the current code (master) this issue should be fixed by commit https://github.com/rodjek/puppet-lint/commit/1cf7bc224f21be647a748e87bf25fdf0f963fc3b authored by @rodjek  which resolved issue #409.

**Comment by SDpyro** [comment] 2016-05-18 00:15
+1

**Comment by rnelson0** [comment] 2016-06-22 13:14
Puppet-lint 2.0.0 is now available. It was previously identified that this issue was fixed in master, but please confirm that you no longer see this behavior with 2.0.0 before we close the ticket. Thank you!

**Comment by rnelson0** [comment] 2016-06-25 04:08
I was able to validate that with the manifest:
```
class test {
  package { 'something': ensure => purged,
    notify => Service['foobar'],
  }
}
```
puppet-lint is able to properly run and detect 1 error and 2 warnings.

**Closed by rnelson0** 2016-06-25 04:08 UTC
