### ISSUE TITLE
Hash of hashes with long keys causes irrational warnings and crashes --fix

### ISSUE THREAD

**Issue by TomOnTime** [rodjek/puppet-lint#424] opened 2015-06-09 13:29 UTC
`puppet-lint --fix example.pp` crashes with this code.

```
#
class example (
  $tiername,
  $external_ip_base,
) {
  stacklb::external::ssl_listener { "${tiername}-1":
    id     => 1,
    inputs => {
      'ny' => {
        "${external_ip_base}.16:443"  => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.17:443"  => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.30:443"  => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.18:443"  => $stacklb::external::params::ssl_wc_san,
        '10.0.0.10:443'               => $stacklb::external::params::ssl_wc_se_internal,
        "${external_ip_base}.24:443"  => $stacklb::external::params::ssl_misc,
        "${external_ip_base}.140:443" => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.141:443" => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.154:443" => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.142:443" => $stacklb::external::params::ssl_wc_san,
        "${external_ip_base}.148:443" => $stacklb::external::params::ssl_misc,
      },
      'or' => {
        '10.10.100.16:443' => $stacklb::external::params::ssl_wc_san,
        '10.10.100.17:443' => $stacklb::external::params::ssl_wc_san,
        '10.10.100.30:443' => $stacklb::external::params::ssl_wc_san,
        '10.10.100.18:443' => $stacklb::external::params::ssl_wc_san,
        '10.0.0.10:443'    => $stacklb::external::params::ssl_wc_se_internal,
        '10.10.100.24:443' => $stacklb::external::params::ssl_misc,
      }
    }
  }
}
```

Without `--fix` you get conflicting requirements.  As-is, it gives these warnings:

```
$ puppet-lint   example.pp 
ERROR: example not in autoload module layout on line 2
WARNING: indentation of => is not properly aligned on line 10
WARNING: indentation of => is not properly aligned on line 11
WARNING: indentation of => is not properly aligned on line 12
WARNING: indentation of => is not properly aligned on line 13
WARNING: indentation of => is not properly aligned on line 14
WARNING: indentation of => is not properly aligned on line 15
WARNING: indentation of => is not properly aligned on line 16
WARNING: indentation of => is not properly aligned on line 17
WARNING: indentation of => is not properly aligned on line 18
WARNING: indentation of => is not properly aligned on line 19
WARNING: indentation of => is not properly aligned on line 20
WARNING: line has more than 80 characters on line 14
```

I hacked puppet-lint to expose what alignment it was expecting.  When I aligned things that way, it warned me that this alignment was incorrect too.  No wonder --fix crashes.

**Comment by rnelson0** [comment] 2016-06-25 04:12
@TomOnTime I am closing this as a duplicate of #416, please re-open it if you feel that is incorrect.

**Comment by TomOnTime** [comment] 2016-06-25 14:56
This is a different issue.  The test case still exhibits the same problem with version 2.0.0

By the way... it would be great if the warning output what column was expected for =>

**Comment by TomOnTime** [comment] 2016-06-25 14:57
@rnelson0 P.S. I don't see how to re-open the issue. (sorry!)

**Comment by rnelson0** [comment] 2016-06-28 17:54
This issue is the result of [check_whitespaces.rb](https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/plugins/check_whitespace.rb#L114-L116) looking at the length of the previous indent token, then the [previous code token](https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/lexer.rb#L280-L287), and getting an unexpected value. By adding a debug print statement `puts "token is #{token.inspect} with #{token.prev_code_token.inspect}"` at the end of the latter block, we can see what the tokens and previous codes look like for lines 10 and 14:
```
        "${external_ip_base}.16:443"  => $stacklb::external::params::ssl_wc_san,           #line 10
        '10.0.0.10:443'               => $stacklb::external::params::ssl_wc_se_internal,   #line 15

token is <Token :INDENT (        ) @10:1> with nil
token is <Token :DQPRE () @10:9> with <Token :LBRACE ({) @9:15>
token is <Token :VARIABLE (external_ip_base) @1:1> with nil
token is <Token :VARIABLE (external_ip_base) @10:11> with <Token :DQPRE () @10:9>
token is <Token :DQPOST (.16:443) @10:29> with <Token :VARIABLE (external_ip_base) @10:11>
token is <Token :WHITESPACE (  ) @10:37> with nil
token is <Token :FARROW (=>) @10:39> with <Token :DQPOST (.16:443) @10:29>
token is <Token :WHITESPACE ( ) @10:41> with nil
token is <Token :VARIABLE (stacklb::external::params::ssl_wc_san) @10:42> with <Token :FARROW (=>) @10:39>
token is <Token :COMMA (,) @10:80> with <Token :VARIABLE (stacklb::external::params::ssl_wc_san) @10:42>
token is <Token :NEWLINE (
) @10:81> with nil

token is <Token :INDENT (        ) @14:1> with nil
token is <Token :SSTRING (10.0.0.10:443) @14:9> with <Token :COMMA (,) @13:80>
token is <Token :WHITESPACE (               ) @14:24> with nil
token is <Token :FARROW (=>) @14:39> with <Token :SSTRING (10.0.0.10:443) @14:9>
token is <Token :WHITESPACE ( ) @14:41> with nil
token is <Token :VARIABLE (stacklb::external::params::ssl_wc_se_internal) @14:42> with <Token :FARROW (=>) @14:39>
token is <Token :COMMA (,) @14:88> with <Token :VARIABLE (stacklb::external::params::ssl_wc_se_internal) @14:42>
token is <Token :NEWLINE (
) @14:89> with nil
```
When the interpolated value is found, rather than discovering `"${external_ip_base}.16:443"` as a single token, it is broken into a DQPRE, VARIABLE, and DQPOST series of tokens, thereby breaking it up and leaving line 14's `'10.0.0.10:443'` statement as the longest token to align with.

This doesn't fix the issue, but identifies where it is so we can attack it.

**Closed** 2017-02-04 00:11 UTC
Labels: puppethack
