### ISSUE TITLE
Error not handled

### ISSUE THREAD

**Issue by RicardoJSTeixeira** [rodjek/puppet-lint#745] opened 2017-09-11 14:57 UTC
---
puppet-lint version: 2.3.0
ruby version: 2.4.1-p111
platform: x64-mingw32
file path: C:\Users\geral\PhpstormProjects\puppet\modules\ipcentrex\manifests\first_step.pp
file contents:
```
#Fscloud instalation first step before base install

#the path => /tmp/repos/ipcentrex.git/install
#tem de ser no tmp pois o opt é alterado e encryptado durante a instalacao

#this is my validation for first step installation: '/usr/bin/test -d /storage'

class ipcentrex::first_step inherits ipcentrex {

  contain ipcentrex::first_step::packages
  contain ipcentrex::first_step::repo
  contain ipcentrex::first_step::config
  contain ipcentrex::first_step::install

  Class['ipcentrex::first_step::packages']
  -> Class['ipcentrex::first_step::repo']
  -> Class['ipcentrex::first_step::config']
  -> Class['ipcentrex::first_step::install']

}

class ipcentrex::first_step::repo inherits ipcentrex {

  file { '/tmp/repos/':
    ensure => 'directory'
  }

  vcsrepo { '/tmp/repos/ipcentrex.git':
    ensure   => present, #latest if you want
    provider => git,
    source   => 'https://fscloudservices:fscloud123$@github.com/finesource/ipcentrex.git',
    revision => 'master',
    require  => File['/tmp/repos/']
  }

}

class ipcentrex::first_step::config inherits ipcentrex {

  file { '/tmp/repos/ipcentrex.git/install/fscloud.config':
    ensure  => present,
    source  => '/tmp/repos/ipcentrex.git/install/fscloud.config.example',
    replace => 'no'
  }

  $defaults = {
    'path' => '/tmp/repos/ipcentrex.git/install/fscloud.config'
  }

  if $isDev {
    $voice_autostart = "'true'"
    $server_env = 'development'
  }
  else {
    $voice_autostart = "'false'"
    $server_env = 'production'
  }

  $ipcentrex_conf = {
    "" => {
      'WAN_IP'                  => "'${wan_ip}'",
      'WAN_HOST'                => "'${wan_host}'",
      'LAN_IP'                  => "'${lan_ip}'",
      'FSCLOUD_VOICE_AUTOSTART' => $voice_autostart,
      'FS_SERVER_ENV'           => $server_env,
      'SECURITY_PACKAGES'       => $security_packages,
      'NTP_SERVER_ENABLED'      => $ntp_server_enabled,
      'HTTPD_ENABLED'           => $httpd_enabled,
      'PGSQL_INSTALL'           => $pgsql_install,
      'PGSQL_ENABLED'           => $pgsql_enabled,
      'MONGODB_INSTALL'         => $mongodb_install,
      'MONGODB_ENABLED'         => $mongodb_enabled,
      'REDIS_INSTALL'           => $redis_install,
      'REDIS_ENABLED'           => $redis_enabled,
      'RPM_REPO_ADDR'           => $vnp_gateway,
      'FSCONTACT_GIT_TAG'       => $fscontact_git_tag,
      'FSCLOUD_API_GIT_TAG'     => $fscloud_api_git_tag,
      'FSCLOUD_API_MASTER_ADDR' => $fscloud_api_master_addr,
      'FACEBOOK_CLIENT_ID'      => $facebook_client_id,
      'FACEBOOK_SECRET'         => $facebook_secret,
      'FSCLOUD_PGHOST'          => "'${fscloud_pghost}'",
      'CDR_PGHOST'              => "'${cdr_pghost}'",
      'KAM_PGHOST'              => "'${kam_pghost}'",
    }
  }

  create_ini_settings($ipcentrex_conf, $defaults)

}

class ipcentrex::first_step::packages inherits ipcentrex {

  if($isDev) {
    exec { 'yum groupinstall Development Tools':
      command   => 'yum -y groupinstall "Development Tools"',
      unless    => 'yum grouplist "Development Tools" | grep "^Installed"',
      logoutput => 'on_failure',
      timeout   => 600
    }
  }else {
    exec { 'yum install gcc':
      command   => 'yum -y gcc gcc-c++',
      logoutput => 'on_failure',
    }
  }

  $aPackages = ['avahi', 'avahi-compat-libdns_sd', 'avahi-compat-libdns_sd-devel', 'git'];

  package { $aPackages: ensure => 'installed' }

  exec { 'install http-parser _ dependency for npm _ bug from Centos before 7.4':
    command   =>
      'rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-devel-2.7.1-3.el7.x86_64.rpm'
    ,
    logoutput => 'on_failure',
  }

}

class ipcentrex::first_step::install inherits ipcentrex {

  exec { 'fscloud-base install':
    command   => 'sh fscloud-base.sh -y',
    cwd       => '/tmp/repos/ipcentrex.git/install',
    creates   => '/etc/yum.repos.d/finesource.repo',
    logoutput => 'on_failure',
    timeout   => 900
  }

  if($isDev) {
    service { 'iptables':
      ensure  => 'stopped',
      enable  => false,
      require => Exec['fscloud-base install'],
    }

  }

}
```
error:
```
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with CP850 string)
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/140chars.rb:11:in `scan'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/140chars.rb:11:in `block in check'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/140chars.rb:9:in `each'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/140chars.rb:9:in `each_with_index'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/plugins/check_whitespace/140chars.rb:9:in `check'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
C:/tools/ruby24/bin/puppet-lint:22:in `load'
C:/tools/ruby24/bin/puppet-lint:22:in `<main>'
```
(anonymous) @ C:\Users\geral\.atom\packages\linter\lib\linter-registry.js:159

**Comment by rodjek** [comment] 2017-09-26 06:10
This looks like a dupe of #693, which was fixed in #730 and will be part of the next release.

**Closed by rodjek** 2017-09-26 06:10 UTC
