### ISSUE TITLE
Nested future scope blocks lose local variables from parent scopes.

### ISSUE THREAD

**Issue by jearls** [rodjek/puppet-lint#456] opened 2015-12-02 21:52 UTC
The future parser allows for nested lambdas.  As a silly but functional example:

    $x = [1,2]
    $x.each |$y| {
        $x.each |$z| {
            notify { "${y}${z}": }
        }
    }

This is valid, and produces 4 notifies with titles `11`, `12`, `21`, and `22`.

However, puppet-lint wil compain about `${y}` in the `notify` on line 4, giving the warning

    WARNING: top-scope variable being used without an explicit namespace on line 4

This also appears in the following situation:

    $x = [ [1,2], [3,4] ]
    $x.each |$y| {
        $y.each |$z| {
            notify { "${z}": }
        }
    }

In this case, puppet-lint will complain about `$y` in line 3, because puppet-lint's scoped variable list for a future scope block "takes over" the scoped variable list for the entire line which includes the beginning of the scope block.

**Comment by dvorak** [comment] 2016-02-15 13:32
Just ran into the same problem here.

**Comment by rnelson0** [comment] 2016-08-18 19:29
Duplicate of #464, which has a bit more discussion.

**Closed by rnelson0** 2016-08-18 19:29 UTC
Labels: puppet4
