### ISSUE TITLE
Improper "unquoted node name found"

### ISSUE THREAD

**Issue by cyberious** [rodjek/puppet-lint#904] opened 2019-11-07 00:16 UTC
I have a function that is used for ExecutionResult sets and checks them... and I am getting unquoted node name found b/c the function is written in puppet.

Exepectation is to either ignore these in a function or fix the issue with regards to this in a function.

functions/process_result.pp:57:38: unquoted node name found

```
// offending declaration is reported as the `.ok` 
if ($abort_on_errors and !$results.ok) { 
    alert(@(EOT))
      Aborting plan due to task failure
    | EOT
    pe::exit(1)
  }```

**Comment by usev6** [comment] 2019-11-15 07:04
I'm not able to reproduce this problem with the code you pasted (neither on HEAD nor with one of the recent releases).

```
$ cat gh/manifests/issue904.pp
## gh issue 904
class gh::issue904 {
  if ($abort_on_errors and !$results.ok) {
    alert(@(EOT))
      Aborting plan due to task failure
    | EOT
    pe::exit(1)
  }
}
$ puppet-lint gh/manifests/issue904.pp 
WARNING: top-scope variable being used without an explicit namespace on line 3
WARNING: top-scope variable being used without an explicit namespace on line 3
```

@cyberious could you maybe provide a more complete example that shows the failure mode? Also, what version of puppet-lint do you use?

**Comment by cyberious** [comment] 2019-11-16 16:53
When the autofix is enabled it attempts to do `!$results.'ok'` sorry I wasn't clear earlier

**Comment by rodjek** [comment] 2020-02-08 03:30
Closing for now, please feel free to reopen again with more information.

**Closed by rodjek** 2020-02-08 03:30 UTC
Labels: needs-more-info
