### ISSUE TITLE
Create v1.1.1

### ISSUE THREAD

**Issue by struys** [rodjek/puppet-lint#401] opened 2015-03-09 17:51 UTC
I'm unable to use puppet-lint because of #364.

**Comment by struys** [comment] 2015-03-12 18:56
bump. I really don't want to fork :(

**Comment by cyberious** [comment] 2015-11-15 06:13
Agreed, need a release

**Comment by rnelson0** [comment] 2016-06-16 12:44
Duplicate of #443

**Closed by rnelson0** 2016-06-16 12:44 UTC
