### ISSUE TITLE
Chaining results in 'whitespce between reference type and title'

### ISSUE THREAD

**Issue by ju5t** [rodjek/puppet-lint#546] opened 2016-09-04 19:30 UTC
`Exec <| title == 'apt_update' |> -> Package <| |>` seems to result in `manifests/apt.pp - ERROR: whitespce between reference type and title on line 65` whereas `Yumrepo <| |> -> Package <| |>` is fine. 

Am I missing something here or is this a bug in puppet-lint?

**Comment by ghoneycutt** [comment] 2016-09-06 21:43
Could not reproduce with puppet-lint v2.0.2

```puppet
Exec <| title == 'apt_update' |> -> Package <| |>
```

```
$ puppet-lint foo.pp
WARNING: spaceship operator without tag on line 1
```

**Comment by ju5t** [comment] 2016-09-07 14:36
I completely forgot to test the line by itself and when I do it checks out. It seems to be related to apt::key.

```
apt::source { 'somerepo':
    ensure       => $ensure_source,
    comment      => 'Somerepo mirror',
    location     => 'http://somerepo.com/mirror',
    repos        => 'main us2',
    release      => $::lsbdistcodename,
    architecture => 'amd64',
    require      => Apt::Key['somerepo'],
}
Class['apt::update'] -> Package <| provider == 'apt' |>
```
Results in 

```
ERROR: whitespce between reference type and title on line 10
```

There are no errors when I remove the dependency on Apt::Key['somerepo']. When I remove the chained resources there are no issues either. It feels like I'm missing something.

**Comment by ghoneycutt** [comment] 2016-09-07 15:58
What version of puppet-lint are you using?

With v2.0.2, I was not able to reproduce the issue. No errors were raised with the code above.

**Comment by ju5t** [comment] 2016-09-10 18:16
I'm running 2.0.2 as well, but the same error occurs with 2.0.0.

```
air:~ ju5t$ cat test.pp
apt::source { 'somerepo':
    ensure       => $ensure_source,
    comment      => 'Somerepo mirror',
    location     => 'http://somerepo.com/mirror',
    repos        => 'main us2',
    release      => $::lsbdistcodename,
    architecture => 'amd64',
    require      => Apt::Key['somerepo'],
}
Class['apt::update'] -> Package <| provider == 'apt' |>
air:~ ju5t $ puppet-lint -v
puppet-lint 2.0.2
air:~ ju5t $ puppet-lint test.pp
ERROR: whitespce between reference type and title on line 10
```

**Comment by ghoneycutt** [comment] 2016-09-11 20:42
Suggest posting the code above as a gist or a link to it already existing on github. Perhaps there is a copy/paste issue preventing me from reproducing.

**Comment by ju5t** [comment] 2016-09-14 20:36
Sorry for the delay. I've pasted the source here: [puppet-lint-error](https://gist.githubusercontent.com/ju5t/3344d6e96e6c09817fe87829cc985de5/raw/77e067b09fbfc83ea3d7882d246b3f46b70b0d5c/puppet-lint-error).

**Comment by ghoneycutt** [comment] 2016-09-15 14:22
@ju5t unable to replicate. Suggest removing puppet-lint and reinstalling.

**Comment by ju5t** [comment] 2016-09-15 18:16
It seems to be an issue with Ruby 2.1.1 although 2.2.5 has the same result. If I try it on 1.9.3-p484 it all works.

This is on 2.2.1:

```
air:~ ju5t $ rbenv shell 2.2.1
air:~ ju5t $ rbenv shell
2.1.1
air:~ ju5t $ puppet-lint test.pp
ERROR: whitespce between reference type and title on line 10
```

And on 1.9.3-p484:

```
air:~ ju5t $ rbenv shell 1.9.3-p484
air:~ ju5t $ rbenv shell
1.9.3-p484
air:~ ju5t $ puppet-lint test.pp
air:~ ju5t $
```

**Comment by ghoneycutt** [comment] 2016-09-15 21:37
@ju5t I think you have an issue with your ruby environment. I was able to get it to work without errors using ruby 2.2.1 and puppet-lint 2.0.2.

```bash
$ wget https://gist.githubusercontent.com/ju5t/3344d6e96e6c09817fe87829cc985de5/raw/77e067b09fbfc83ea3d7882d246b3f46b70b0d5c/puppet-lint-error -O foo.pp

2016-09-15 17:35:57 (3.43 MB/s) - ‘foo.pp’ saved [352/352]

$ puppet-lint foo.pp ; echo $?
0
$ puppet-lint --version
puppet-lint 2.0.2
$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

**Comment by rnelson0** [comment] 2016-10-05 14:27
@ju5t I am going to close this out as it looks like a ruby/environment issue, but please let us know if you can replicate it elsewhere and we can take another look. Thanks!

**Closed by rnelson0** 2016-10-05 14:27 UTC
