### ISSUE TITLE
PuppetLint.configuration.ignore_paths not working 1.1.0

### ISSUE THREAD

**Issue by edestecd** [rodjek/puppet-lint#355] opened 2014-10-29 16:14 UTC
If you define:

PuppetLint.configuration.ignore_paths in Rakefile
it will not work and the ignore paths will be linted.

Environment:
- ruby '2.1.2', :engine => 'ruby', :engine_version => '2.1.2', :patchlevel => '95'
- puppet-lint (1.1.0)
- rake (10.3.2)

**Comment by tuxinaut** [comment] 2015-03-26 17:17
Any progress?

**Comment by edestecd** [comment] 2015-03-26 19:50
I'm not sure if this is fixed.  I have it locked to 1.0.1 in me Gemfiles.
I guess I need to test on newer versions.  Are you still having this issue?

**Comment by tuxinaut** [comment] 2015-03-27 08:29
Yes I have still this issue with version **1.1.0**

**Comment by brettswift** [comment] 2016-06-14 14:02
over a year later..  Is this bug forgotten? Still broken on 1.1.0.

**Comment by rnelson0** [comment] 2016-06-14 14:46
It's been a while and between this and #331, I think the problem is that you expect to use:
```
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "vendor/**/*.pp", "modules/**/*.pp"]
```
But instead you must use (from #331):
```
Rake::Task[:lint].clear
PuppetLint::RakeTask.new :lint do |config|
  config.ignore_paths   = ["spec/**/*.pp", "vendor/**/*.pp", "modules/**/*.pp"]
end
```
Is that a correct summary?

**Comment by rnelson0** [comment] 2016-11-27 04:33
@edestecd @brettswift Can you review and see if this is still an issue with 2.0.x or HEAD? Thanks!

**Comment by es1o** [comment] 2016-12-07 08:18
@rnelson0 
Hi, I use puppet-lint 2.0.2 and for me works this configuration in Rakefile:
'require 'puppet-lint/tasks/puppet-lint'

PuppetLint::RakeTask.new :lint do |config|
    config.ignore_paths = ["modules/stdlib/**/*.pp"]
end
'

**Comment by brettswift** [comment] 2016-12-12 15:32
@rnelson0   6 months later..    tested and works!

**Comment by rnelson0** [comment] 2016-12-12 16:17
Thanks for verification all. Closing this out.

**Closed by rnelson0** 2016-12-12 16:17 UTC
Labels: needs-more-info
