### ISSUE TITLE
Error with puppet-lint --fix: NoMethodError: undefined method `next_token' for nil:NilClass

### ISSUE THREAD

**Issue by jaredgaut** [rodjek/puppet-lint#831] opened 2018-08-24 19:02 UTC
Whoops! It looks like puppet-lint has encountered an error that it doesn't
know how to handle. Please open an issue at https://github.com/rodjek/puppet-lint
and paste the following output into the issue description.
---
puppet-lint version: 2.3.3
ruby version: 2.3.7-p456
platform: universal.x86_64-darwin18
file path: ./elk/manifests/java.pp
file contents:
```
class java::oracle_java8 {

  # This follows the recipe from http://blog.nocturne.net.nz/devops/2013/08/14/provisioning-oracle-java-with-puppet-apply/
  # adapted with the instructions from http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

  # define a variable for the webupd8team ppa sources list
  $webupd8src = '/etc/apt/sources.list.d/webupd8team.list'

  exec {'hello':
    unless => "/bin/true",
    command => '/bin/echo hello world',
  }

  # Configure ppa
  file { $webupd8src:
    content => "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main\ndeb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main\n",
    } ->
    # Authorise the webupd8 ppa
    # At the time of writing this key was correct, but check the PPA page on launchpad!
    # https://launchpad.net/~webupd8team/+archive/java
    exec { 'add-webupd8-key':
      unless => "apt-key list | grep -c EEA14886 2>/dev/null",
      command => 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886',
      path => ['/usr/bin/','/bin/'],
      } ->
      # update the apt keystore
      exec { 'apt-key-update':
        unless => "update-alternatives --list java|grep java-8-oracle 2>/dev/null",
        command => 'apt-key update',
        path => ['/usr/bin/','/bin/'],
        } ->
        # update apt sources
        exec { 'apt-update':
          unless => "update-alternatives --list java|grep java-8-oracle 2>/dev/null",
          command => 'apt-get update',
          path => ['/usr/bin/','/bin/'],
          } ->
          # set license acceptance with debconf
          exec { 'accept-java-license':
            unless => "update-alternatives --list java|grep java-8-oracle 2>/dev/null",
            command => 'echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections',
            path => ['/usr/bin/','/bin/'],

            } ~>
            # finally install the package
            # oracle-java6-installer and oracle-java7-installer also available from the ppa
            package { 'oracle-java8-installer':
              ensure => present,
            }
}


```
error:
```
NoMethodError: undefined method `next_token' for nil:NilClass
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:196:in `find_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:142:in `next_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:189:in `find_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:142:in `next_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:189:in `find_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/lexer/token.rb:142:in `next_token_of'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:176:in `block in resource_indexes'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:171:in `each'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/data.rb:171:in `resource_indexes'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:81:in `resource_indexes'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/plugins/check_resources/ensure_first_param.rb:8:in `check'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:60:in `block in run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:59:in `block in run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `each'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `run'
/Users/jgaut/.gem/ruby/2.3.0/gems/puppet-lint-2.3.3/bin/puppet-lint:7:in `<main>'
```

**Comment by rodjek** [comment] 2019-09-28 01:36
I'm unable to reproduce this error with the above manifest on 2.3.3. From the look of the stack trace though, it appears to be a duplicate of the error that was resolved by #875. Please reopen the issue if it still occurs with the next release of puppet-lint.

**Closed by rodjek** 2019-09-28 01:36 UTC
