### ISSUE TITLE
TypeError running on seemingly-sane puppet file

### ISSUE THREAD

**Issue by deltamualpha** [rodjek/puppet-lint#399] opened 2015-02-25 19:02 UTC
running puppet-lint on https://github.com/ajjahn/puppet-samba/blob/master/manifests/server/ads.pp causes a TypeError crash. By chopping out various bits of the file and re-running, I've isolated it down to this line: https://github.com/ajjahn/puppet-samba/blob/master/manifests/server/ads.pp#L55

Full stacktrace, if helpful:
```/Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `[]': no implicit conversion from nil to integer (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:115:in `block (2 levels) in check'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:111:in `block in check'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/plugins/check_whitespace.rb:95:in `check'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checkplugin.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:58:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/checks.rb:56:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint.rb:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:59:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/lib/puppet-lint/bin.rb:56:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/puppet-lint-1.1.0/bin/puppet-lint:7:in `<top (required)>'
	from /usr/bin/puppet-lint:23:in `load'
	from /usr/bin/puppet-lint:23:in `<main>'```

**Comment by rodjek** [comment] 2015-04-12 02:09
Dupe of #409

**Closed by rodjek** 2015-04-12 02:09 UTC
