### ISSUE TITLE
In mixed tab-space files, sometimes whitespace calculations are negative

### ISSUE THREAD

**Issue by binford2k** [rodjek/puppet-lint#482] opened 2016-06-24 20:40 UTC
Context is explained in #445 

The manifest in question starts out with space indentation, then switches to tabs. Because of this the indentation check becomes negative, when it tries to subtract the proper number of space characters.

We should either ensure that the 2 sp soft tab fix runs first, or we should improve the algorithm to calculate indentation.

**Comment by rnelson0** [comment] 2016-08-18 19:22
@binford2k this should be fixed in 2.0.1, can you check and validate that?

**Comment by rnelson0** [comment] 2016-10-05 14:20
@binford2k bump for verification

**Comment by rnelson0** [comment] 2016-12-19 00:23
Duplicate of #366. Closing.

**Closed by rnelson0** 2016-12-19 00:23 UTC
Labels: duplicate
